name: Build IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.4'

    - name: Install dependencies
      run: flutter pub get

    - name: Install CocoaPods
      run: |
        cd ios
        pod install
        cd ..

    - name: Build IPA
      run: flutter build ipa --release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa
        path: build/ios/ipa/*.ipa
